### ISSUE TITLE
CopyClips: website link broken.

### ISSUE THREAD

**Issue by politicus** [raguay/MyAlfred#12]
The workflow's website links leads to a 404 page. 

And while I am at it, the link to your workflows on this [page](http://www.customct.com/favtools/) is broken too.

**Comment by raguay** [comment]
Yes. Many links are messed up because I'm transitioning from a VPS using my own server to a github pages account using static pages. I started with hugo, but now transitioning to my own version based on Svelte since I'm having issues with getting hugo to do what I want.
