### ISSUE TITLE
Caffeinate not working

### ISSUE THREAD

**Issue by KyleKing** [raguay/MyAlfred#4]
When triggered, my computer will still go to sleep within a few minutes

**Comment by raguay** [comment]
You are talking about the Mjolnir workflow, correct? Yea, that is a add-on library to Mjolnir. I have asked the author about it, but he never got back to me. It seems to work some, but not completely. I use Caffeine free program myself.

**Comment by raguay** [comment]
I no longer support the Mjolnir workflow, but I have moved everything over to the Hammerspoon workflow and added to it. The caffeinated for Hammerspoon works fine and is completely self-contained. I would recommend moving to that program instead of Mjolnir.
