### ISSUE TITLE
Alfred Browser Toolbox throws error when Commander One isn't installed.

### ISSUE THREAD

**Issue by brianroach** [raguay/MyAlfred#7]
Tried using the ab:mparent feature on a series of selected files, but a window popped up asking me where Commander One was installed.

**Comment by raguay** [comment]
The workflow only works on one file at a time. If for some reason you did not have the top most window being either Finder, or Path Finder, or Commander One, it will end up testing for each one of these until it finds one. If one of them isn't installed on your system, it will complain that it doesn't know what program that is.
